### ISSUE TITLE
Installing all necessary packages to compile learn resources in one sweep

### ISSUE THREAD

**Issue by hoehleatsu** [reconhub/learn#8]
Is there a clever way to install all necessary packages to have blogdown compile the learn ressources in one sweep? Spent 30 minutes continously installing additional packages before the thing compiled...

**Comment by thibautjombart** [comment]
This is being discussed as a project for tomorrow's hackathon:
https://github.com/RECON-gathering-March-2018/projects/issues/6

**Comment by thibautjombart** [comment]
The recommended approach (now in the `README`) is:
```
if (!require("checkpoint")) {
    install.packages("checkpoint")
}

install.packages(
    checkpoint::scanForPackages(use.knitr = TRUE)$pkgs
)
```
